Api/urls.py
from django.conf.urls import include, url
from Api.views import *
from django.views.decorators.csrf import csrf_exempt
from Service.views import *

urlpatterns = [
    url(r"^CMDBApi/", csrf_exempt(CMDBApi.as_view())),
    url(r"^$",server),
    url(r"^(?P<page>\d+)", server),
    url(r"^ajax_server/$", AjaxServer),
    url(r"^ajax_server/(?P<page>\d+)/$", AjaxServer),
    url(r"^sj/$", ServerList_ajax),
    url(r"^getConnect/$",getConnect),
    url(r"^gateValid/$",gateValid)
]

cmdb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from Users.views import *
from cmdb.views import *
from Api.views import *

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    url(r'^index/', index,name='index'),
    url(r'^$', index),
    url(r'^echart/', echartExample),
    url(r'^user/', include("Users.urls")),
    url(r'^login/', login,name='login'),
    url(r'^api/',include("Api.urls")),
    url(r'^server/', include("Api.urls")),
    url(r'^vue/',vueExample),
    url(r'^gate/',gate),
]

Users/forms.py
# coding:utf-8
# @mail:879995812@qq.com

from django import forms

# 用来改善前端form的难看的样式

class CMDBUserForm(forms.Form):
    username = forms.CharField(max_length=32, label="用户账号", widget=forms.TextInput(
        attrs={
            "class": "form-control",
            "required": "",
            "minlength": 2,
            "maxlength": 32
        }))
    # 前面是后端验证，widget是前端验证
    password = forms.CharField(max_length=32, label="用户密码", widget=forms.PasswordInput(
        attrs={
            "class": "form-control",
            "required": "",
            "minlength": 2,
            "maxlength": 32
        }))
    nickname = forms.CharField(max_length=32, label="用户姓名", widget=forms.TextInput(
        attrs={
            "class": "form-control",
            "required": ""
        }))
    phone = forms.CharField(max_length=32, label="用户电话", widget=forms.TextInput(
        attrs={
            "class": "form-control",
            "required": ""
        }))
    email = forms.EmailField(label="用户邮箱", widget=forms.EmailInput(
        attrs={
            "class": "form-control",
            "requeired": ""
        }))
    photo = forms.ImageField(label="用户头像")

    def clean_phone(self):
        # 获取前端提交的值
        data = self.cleaned_data["phone"]
        if len(data) < 11:  # 进行条件判断
            raise forms.ValidationError("手机号不可以小于11为")  # 如果不满足条件，提出错误
        else:
            return data  # 如果满足条件返回正确的值

    # 请写方法校验上传的照片大小

templates/ServerList.html
{% extends "blank.html" %}

{% block title %}
    服务器列表
{% endblock %}

{% block label %}
    服务器列表
{% endblock %}

{% block content %}
    <!--表格开始-->
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                        <tr>
                            <th>hostname</th>
                            <th>ip</th>
                            <th>mac</th>
                            <th>cpu</th>
                            <th>memory</th>
                            <th>isalive</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for data in pageData %}
                            <tr>
                                <td class="warning">
                                    <a href="/server/getConnect/?id={{ data.id }}">
                                        {{ data.hostname }}
                                    </a>
                                </td>
                                <td class="success">{{ data.ip }}</td>
                                <td class="info">{{ data.mac }}</td>
                                <td class="warning">{{ data.cpu }}</td>
                                <td class="info">{{ data.memory }}</td>
                                <td class="success">{{ data.isalive }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <!-- /.table-responsive -->
                    <ul class="pagination pull-right">
                        {% for page in pageRange %}
                            <li>
                                <a href="/server/{{ page }}/">{{ page }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <!--表格结束-->
{% endblock %}

templates/ServerList_ajax.html
{% extends "blank.html" %}

{% block title %}
    服务器列表
{% endblock %}
{% block style %}
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/js/vue.js"></script>
    <script src="/static/js/vue-resource.js"></script>
{% endblock %}

{% block label %}
    服务器列表_ajax
{% endblock %}

{% block content %}
    <!--表格开始-->
    <!-- /.row -->
    {% verbatim myblock %}
        <div class="row" id="serverData">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <table width="100%" class="table table-striped table-bordered table-hover"
                               id="dataTables-example">
                            <thead>
                            <tr>
                                <th>hostname</th>
                                <th>ip</th>
                                <th>mac</th>
                                <th>cpu</th>
                                <th>memory</th>
                                <th>isalive</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr class="odd gradeX" v-for="data in page_data">
                                <td>
                                    <a href="{{ data.id }}">
                                        {{ data.hostname }}
                                    </a>
                                </td>
                                <td>{{ data.ip }}</td>
                                <td>{{ data.mac }}</td>
                                <td>{{ data.cpu }}</td>
                                <td>{{ data.memory }}</td>
                                <td>{{ data.isalive }}</td>
                            </tr>
                            </tbody>
                        </table>
                        <!-- /.table-responsive -->
                        <ul class="pagination pull-right">
                            <li v-for="page in page_range">
                                <a v-on:click="getPage(page)">{{ page }}</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
    {% endverbatim myblock %}
    <!--表格结束-->
    <script>
        Vue.use(VueResource);// 强调使用vue_resource.js
        new Vue(
            {
                el: "#serverData",
                data: {
                    page_data: "", //页面数据
                    page_range: "" //页码数据
                },
                created: function () {
                    var url = "/server/ajax_server/";
                    this.$http.get(url).then(
                        function (data) {
                            console.log(data);
                            var Data = data.data;
                            this.page_data = Data.page_data;
                            this.page_range = Data.page_range

                        },
                        function (error) {
                            console.log(error)
                        }
                    ); //vue_resource.js自带的ajax请求方法
                },//初始
                methods: {
                    getPage: function (page) {
                        var url = "/server/ajax_server/" + page;
                        this.$http.get(url).then(
                            function (data) {
                                console.log(data.data);
                                var Data = data.data;
                                this.page_data = Data.page_data;
                                this.page_range = Data.page_range
                            },
                            function (error) {
                                console.log(error)
                            }
                        );
                    }
                }
            }
        )
    </script>
{% endblock %}

templates/echartExample.html
{% extends "blank.html" %}

{% block title %}
    Echarts-Example
{% endblock %}

{% block style %}
    <script src="/static/js/echarts.min.js"></script>
{% endblock %}

{% block label %}
    Echarts-Example
{% endblock %}

{% block content %}
    <div id="panel" style="height: 500px; width: 500px;"></div>
    <script>
        //初始化画布
        var myChart = echarts.init(document.getElementById("panel"));
        //定义选项参数
        options = {
            title: {
                text: "我的柱状图"
            },
            tooltip: {},
            legend: {
                data: ["学科"]
            },
            xAxis: {
                data: ["python", "php", "jave", "linux", "c++"]
            },
            yAxis: {},
            series: [
                {
                    name: "学科",
                    type: "bar",
                    data: [1, 4, 2, 5, 3]
                }
            ]
        };
        myChart.setOption(options)
    </script>
{% endblock %}
{#1、bar#}
{#    柱状图#}
{#2、line#}
{#    折线图#}
{#3、gauge#}
{#    仪表盘#}
{#4、pie#}
{#    饼状图#}
{#5、island#}
{#    孤岛图#}
{#6、funnel#}
{#    漏斗图#}

templates/gateoneExample.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>gateoneExample</title>
    <script src="/static/js/gateone.js"></script>
    <script src="/static/vendor/jquery/jquery.min.js"></script>
</head>
<body>
    <div id="gateone_container" style="position: relative;width: 80em;height: 60em">
        <div id="gateone">

        </div>
</div>
</body>
    <script>
        $(
            function () {
                GateOne.init(
                    {url: "https://10.10.10.69:443"}
                )
            }
        )
    </script>
</html>

templates/getConnect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="/static/js/gateone.js"></script>
    <script src="/static/vendor/jquery/jquery.min.js"></script>
</head>
<body>
<div id="gateone_container" style="position: relative; width: 77em; height: 40em;">
    <div id="gateone">

    </div>
</div>
<script>
    $(document).ready(
        function () {
            var ip = "{{ server.ip }}";
            {#var ip = "10.10.10.68";#}
            var port = "22";
            var user = "root";
            var ssh_url = "ssh://" + user + "@" + ip + ":" + port;

            var request = $.ajax({
                url: "/server/gateValid/", //后台的函数，负责校验算法功能,返回地址和认证的信息
                //auth_info.auth  auth_info.url
                type: "GET", //从后台获取来的数据全是GET方式
                dataType: "json"
            });
            request.done(function (auth_info) {
                var auth_message = auth_info.auth;
                var auth_url = auth_info.url;
                console.log("++++++++++++++++++++++++++auth_message+++++++++++++++++++++++++++++++");
                console.log(auth_message);
                console.log("++++++++++++++++++++++++++auth_message_end+++++++++++++++++++++++++++++++");
                console.log("++++++++++++++++++++++++++auth_url+++++++++++++++++++++++++++++++");
                console.log(auth_url);
                console.log("++++++++++++++++++++++++++auth_url_end+++++++++++++++++++++++++++++++");

                GateOne.init({
                    auth: auth_message, //提交认证信息
                    url: auth_url, //认证的地址
                    theme: 'solarized', //认证类型
                    goDiv: '#gateone',  //操作元素
                    disableTermTransitions: 'true', //显示命令行
                    autoConnectURL: ssh_url //默认登录的服务器
                });

            });
            //gateone 官方对gateOne界面进行调试的选项
            GateOne.Base.superSandbox(
                "GateOne.SomePlugin",
                ["GateOne", "GateOne.Net", "GateOne.Terminal.Input", "GateOne.Terminal"],
                function (window, undefined) {
                    var location = ip;
                    GateOne.prefs.autoConnectURL = ssh_url;
                    GateOne.prefs.fontSize = "100%";
                    GateOne.prefs.scrollback = 10000;  // scrollback buffer up to 10,000 lines
                    GateOne.Terminal.loadFont("Source Code Pro", "150%");
                    GateOne.Net.setLocation(location);
                });
        });
</script>
</body>
</html>

templates/get_page.html
{% extends "blank.html" %}

{% block title %}
    get page
{% endblock %}

{% block label %}
    get page
{% endblock %}

{% block content %}
    {{ item }}
{% endblock %}

templates/index.html
{% extends "blank.html" %}

{% block title %}
    服务器管理-首页
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="/static/css/register.css">
{% endblock %}

{% block label %}
    <!--模态框触发部分-->
    <!--
        data-toggle 以何种形式展示模态框 modal popover
        data-target 模态框id
    -->
    <div class="container-fluid">
        <div class="col-md-10">
            CMDB管理-首页
        </div>
        <div class="col-md-1">
            <button class="btn btn-default">
                <a href="{% url 'login' %}">退出</a>
            </button>
        </div>
        <div class="col-md-1">
            <button class="btn btn-default" data-toggle="modal" data-target="#register_user_modal">
                <a>注册</a>
            </button>
        </div>
    </div>
    <!--模态框触发部分结束-->
{% endblock %}

{% block content %}
    <!--模态框面板部分-->
    <!--
       tabindex  tab键导航切换的顺序
       role = dialog 指定展示的样式（角色）为模态框
       aria-labelledby = 设置aria-labelledby的值为某个元素的id，那么浏览器就可以读取它的值。
            当 ul 获取到焦点时，屏幕阅读器会读：“选择你的职业”
       footer 页脚
    -->
    <div class="modal fade" id="register_user_modal" tabindex="-1" role="dialog" aria-labelledby="MyLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <!-- 下面的是关闭按钮 -->
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        x {# data-dismiss="modal" 用来关闭模态框 #}
                    </button>
                    <h4 class="modal-title" id="MyLabel">
                        用户注册
                    </h4>
                </div>
                <form method="post" id="register_Form" enctype="multipart/form-data">
                    <div class="modal-body">
                        {% csrf_token %}
                        {% for form in forms %}
                            <div class="form-group input-group">
                                <span class="input-group-addon">{{ form.label }}</span>
                                {{ form }}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-primary">
                            提交
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!--模态框面板部分结束-->


{% endblock %}


{% block script %}
    <script type="text/javascript" src="/static/vendor/jquery/jquery.validate.min.js"></script>
    <script type="text/javascript" src="/static/vendor/jquery/messages_zh.min.js"></script>

    <script>
        $().ready({# 当DOM加载完成后，执行这个函数 #}
            function () {
                $("#register_Form").validate(
                    {
                        rules: {
                            id_username: {
                                required: true,
                                maxlength: 32,
                                minlength: 2
                            },
                            id_password: {
                                required: true,
                                maxlength: 32,
                                minlength: 2
                            },
                            id_nickname: {
                                required: true,
                                maxlength: 32,
                                minlength: 2
                            },
                            id_phone: {
                                required: true
                            },
                            id_email: {
                                email: true
                            }
                        },
                        messages: {
                            id_username: {
                                required: "用户名不能为空",
                                maxlength: "用户名不能大于6位",
                                minlength: "用户名不能小于2位"
                            },
                            id_password: {
                                required: "密码不能大于6为",
                                maxlength: "密码不能大于6位",
                                minlength: "密码不能小于2位"
                            },
                            id_nickname: {
                                required: "用户姓名不能大于6为",
                                maxlength: "用户姓名不能大于6位",
                                minlength: "用户姓名不能小于2位"
                            },
                            id_phone: {
                                required: "电话不能为空"
                            },
                            id_email: {
                                email: "邮件需要符合格式"
                            }
                        },
                        submitHandler: function (form) {
                            {#form.submit();#}   //单纯的提交给后端，并不是异步提交ajax
                            var formData = new FormData();
                            data = $("#register_Form").serializeArray();
                            for (var d in data) {
                                key = data[d]["name"];   //d是索引，整个data是一个字典
                                value = data[d]["value"];
                                formData.append(key, value)
                            }
                            //填充图片
                            img = $("#id_photo")[0].files[0];   //可以通过F12查看器查看id
                            //console.log(img);
                            formData.append("photo", img);
                            //取csrf的值
                            var csrftoken = data[0]["value"];
                            $.ajax(
                                {
                                    url: "/user/register/",
                                    type: "post",
                                    data: formData,
                                    traditional: true, //是否深度序列化数据,true为不深度(比如有嵌套层)
                                    processData: false,  //是否序列化字符串（有文件，所以不序列化）
                                    contentType: false,  //信息的类型
                                    success: function (data) {
                                        console.log(data)
                                    },
                                    {#beforeSend: function () {#}
                                    {#    // 禁用按钮防止重复提交,防止提交数据库多次脏数据#}
                                    {#    $("#submit").attr({disabled: "disabled"});#}
                                    //},
                                    beforeSend: function (xhr, settings) {
                                        //XMLHttpRequest.setRequestHeader() == xhr.setRequestHeader()
                                        xhr.setRequestHeader("X-CSRFToken", csrftoken)
                                    },//发送数据之前
                                    error: function (error) {
                                        console.log(error)
                                    }
                                }
                            )
                        }
                    }
                )
            }
        )
    </script>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>登陆</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/static/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">欢迎登陆</h3>
                </div>
                <div class="panel-body">
                    <form role="form" method="post">
                        {% csrf_token %}
                        <fieldset>
                            <div class="form-group">
                                <input class="form-control" placeholder="用户名" name="username" type="text" autofocus>
                            </div>
                            <div class="form-group">
                                <input class="form-control" placeholder="密码" name="password" type="password"
                                       value="">
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input name="remember" type="checkbox" value="Remember Me">记住密码
                                </label>
                            </div>
                            <!-- Change this to a button or input when using this as a form -->
                            <input class="btn btn-lg btn-success btn-block" type="submit" value="登陆">
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- jQuery -->
<script src="/static/vendor/jquery/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="/static/vendor/metisMenu/metisMenu.min.js"></script>

<!-- Custom Theme JavaScript -->
<script src="/static/dist/js/sb-admin-2.js"></script>
</body>
</html>

templates/vueExample.html
{% extends "blank.html" %}

{% block title %}
    Vue示例
{% endblock %}

{% block style %}
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/js/vue.js"></script>
{% endblock %}


{% block label %}
    Vue示例
{% endblock %}

{% block content %}
    {% verbatim nameblock %}
        <div id="example">
            <p>
                <span>基本的文本绑定:</span>
                <span>I am {{ name }}</span>
            </p>
            <p>
            <ul>
                <span>基本的循环绑定:</span>
                <li v-for="a in page">{{ a }}</li>
            </ul>
            </p>
            <p>
                <!--
                强调三样
                    1、绑定属性
                    2、绑定多重属性
                    3、绑定字典对象
                -->
                <span>带有属性和映射的循环绑定:</span>
            <ul>
                <li v-for="data in message">
                    <a v-bind:href="data.name" v-bind:class='[data.name,data.cla]'>
                        {{ data.name }}
                    </a>
                </li>
            </ul>
            </p>

            <p>
                <span>基本的事件绑定:</span>
                <button v-on:click="sample_method">按我呀！</button>
            </p>
            <p>
                <span>基于ajax的传参绑定:</span>
            <ul>
                <ul>
                    <li v-for="p in page">
                        <a v-on:click="ajax_method(p)">
                            {{ p }}
                        </a>
                    </li>
                </ul>
            </ul>
            </p>

        </div>
    {% endverbatim nameblock %}
    <script>
        new Vue({
            el: "#example",
            data: {
                name: "Dong",
                page: [1, 2, 3, 4, 5],
                message: [
                    {name: "Bryant", id: 1, cla: "test1"},
                    {name: "T-mac", id: 2, cla: "test2"},
                    {name: "Green", id: 3, cla: "test3"},
                    {name: "Magee", id: 4, cla: "test4"},
                    {name: "Cociey", id: 5, cla: "test5"}
                ],
                ajaxData: ""
            },
            methods: {
                sample_method: function () {
                    alert("hello world!")
                },
                ajax_method: function (page) {
                    $.ajax(
                        {
                            url: "/server/ajax_server/" + page,
                            data: "",
                            type: "get",
                            success: function (data) {
                                console.log(data["page_data"]);
                            },
                            error: function (error) {
                                console.log(error)
                            }
                        }
                    )
                }
            }
        })
    </script>
{% endblock %}